Red and blue teams
BreX900/mek_gasol pull request #3
Opened 2022-05-10 21:15 UTC by matteovalerio

Add text color for teams
Change to Red and Blue teams
Change comma to hyphen

2022-05-10 21:16 UTC, matteovalerio commented
<img width="1196" alt="Schermata 2022-05-10 alle 23 15 40" src="https://user-images.githubusercontent.com/4181493/167723167-53466c32-b6ff-4420-a872-d8785dbfaefe.png">
<img width="1195" alt="Schermata 2022-05-10 alle 23 15 31" src="https://user-images.githubusercontent.com/4181493/167723204-77434463-793e-4c1c-8863-01aec87a9e7b.png">

2022-05-10 21:17 UTC, matteovalerio commented
Ecco il mio contributo serale :smile:

2022-05-11 07:05 UTC, BreX900 commented
Grazie mille. Ma larghezza della pagina a 100 e le virgole :) 
Si potrebbe mergiare ma le specifiche complete le puoi trovare https://github.com/BreX900/mek_gasol/issues/4

2022-05-11 14:58 UTC, BreX900 requested changes
Rebase e vedi messaggio sopra

2022-05-12 21:30 UTC, matteovalerio commented
Ho sistemato la formattazione.
Ho aggiunto io i colori delle squadre al posto dei vari left and right..non sono nelle specifiche però.. li tolgo?

2022-05-12 21:35 UTC, matteovalerio commented
mi correggo, i colori sono sull'issue #5

2022-05-13 06:29 UTC, BreX900 approved these changes

2022-05-13 08:23 UTC, BreX900 requested changes

2022-05-13 08:23 UTC, BreX900 commented on app/lib/presentation/features/match.dart
> +            },
```suggestion
            }
```
Rebase e già che ci sei toglimi questa virgola XD

2022-05-18 06:41 UTC, BreX900 approved these changes

2022-05-18 06:42 UTC, merged